# Generated by Django 5.1.1 on 2024-09-27 13:30

import django.db.models.deletion
import mutual_fund.models.mutual_fund
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FundSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('fund_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_group', to='mutual_fund.fundgroup')),
            ],
        ),
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to=mutual_fund.models.mutual_fund.upload_to)),
                ('desctription', models.TextField()),
                ('sip_enabled', models.BooleanField(default=False)),
                ('minimum_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total_unit', models.IntegerField(default=0)),
                ('fund_sub_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_sub_group', to='mutual_fund.fundsubgroup')),
            ],
        ),
    ]
