# Generated by Django 5.1.1 on 2024-09-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundgroup',
            options={'verbose_name_plural': 'Fund Group'},
        ),
        migrations.AlterModelOptions(
            name='fundsubgroup',
            options={'verbose_name_plural': 'Fund Sub Group'},
        ),
        migrations.AlterModelOptions(
            name='mutualfund',
            options={'verbose_name_plural': 'Mutual Fund'},
        ),
    ]
